[build]
  publish = "dist/balaji-portfolio/browser"

[[redirects]]
  from = "/api/*"
  to = "https://new-portfolio-mean-stack.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
